### ISSUE TITLE
Feature Request - Add thumbnail when sharing a phixiv link with spoiler in Discord

### ISSUE THREAD

**Issue by DisasterInbound** [thelaao/phixiv#2]
Hello.
When sharing a [fx](https://github.com/FixTweet/FxTwitter) or [vx](https://github.com/dylanpdx/BetterTwitFix) twitter link on Discord with spoiler it embeds the thumbnail and still adds a spoiler over the photo/video, like on the picture below. But if I do the same with phixiv it never shows a thumbnail and instead leaves the link under the spoiler.

It would be nice if Phixiv links could also be embed liked this 
![Discord_S93NfAfeGw](https://github.com/thelaao/phixiv/assets/64549167/3a64e2fa-f603-4c83-bc8d-16375e321be2)

Is this possible to add for both normal galleries and ugoiras?

P.S. I also wanted to thank you for keeping the Phixiv service alive.

**Comment by thelaao** [comment]
The problem is that when trying to embed a spoilered link, like ||https://www.phixiv.net/en/artworks/117961932||, the trailing || are considered part of the url, so phixiv was receiving an invalid id. This was fixing by ignoring any extra characters after the numeric id.

**Comment by DisasterInbound** [comment]
@thelaao Hi again, recently it stopped working again. Currently it shows the link inside a spoiler as if it was a normal text message.

**Comment by thelaao** [comment]
> [@thelaao](https://github.com/thelaao) Hi again, recently it stopped working again. Currently it shows the link inside a spoiler as if it was a normal text message.

Fixed
