### ISSUE TITLE
Issue with URL paths [PPixiv]

### ISSUE THREAD

**Issue by AzureZakura** [thelaao/phixiv#3]
Any of the following paths below when embedding with the PPixiv script (https://github.com/ppixiv/ppixiv) active will now not embed after posting the link once. Originally the embed would work normally and embed all links without issue. This occurs on desktop and web browser discord. The embed will also fail if posted by an alternative account. The modifier #ppixiv appears to be conflicting with embed.

/artworks/:id
/:language/artworks/:id
/artworks/:id/:index
/:language/artworks/:id/:index
/member_illust.php?illust_id=:id

Example in image attached
![image](https://github.com/user-attachments/assets/b34fdb76-9497-497f-9e5b-27f06f685007)

**Comment by thelaao** [comment]
The issue seems to be on discord side, I tried this on other embeds and all of them have this problem if the url has a #. If you send a link multiple times, discord caches the embed and phixiv only processes the first request. So there isn't much we can do about it, you should report this issue directly to discord.
![image](https://github.com/user-attachments/assets/ebb41577-044c-421a-9b7b-10a48197a336)

**Comment by AzureZakura** [comment]
Okay thank you for the information

> The issue seems to be on discord side, I tried this on other embeds and all of them have this problem if the url has a #. If you send a link multiple times, discord caches the embed and phixiv only processes the first request. So there isn't much we can do about it, you should report this issue directly to discord. ![image](https://private-user-images.githubusercontent.com/104701180/373650076-ebb41577-044c-421a-9b7b-10a48197a336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNTEzMDksIm5iZiI6MTcyODA1MTAwOSwicGF0aCI6Ii8xMDQ3MDExODAvMzczNjUwMDc2LWViYjQxNTc3LTA0NGMtNDIxYS05YjdiLTEwYTQ4MTk3YTMzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNDEwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGEyYzk0MzM1ODM2MGU2NGM2YmIxZGY0Y2FkOWM3MmU1YjBjNzUwNTFjZTRiZDg3ODU3MjRjYTY1NGI2YjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EXwTbgnu2DkBGzOi_esaszFioifJ_HEzRjXwNz0NTZ0)
