### ISSUE TITLE
Parse HTML in the description for API response

### ISSUE THREAD

**Issue by thmasq** [thelaao/phixiv#4]
I believe it would make sense for the API to return raw text rather than HTML as is being done with the current implementation

**Comment by thmasq** [comment]
I have an example implementation I made on my fork [here](https://github.com/thmasq/phixiv/commit/b966ece244c5b21eacd747cad3632a3512cd09c1). I'm proposing this change because I do not wish to host it any longer. Though for now you can see what it's currently doing here: https://phixiv.squaredfield.com/api/info?id=114258043

**Comment by thelaao** [comment]
The description can have bold, italic, strike-through or colored text. If we return plain text the styling would be lost. Example: https://phixiv.net/api/info?id=96083890

**Comment by thmasq** [comment]
I see, that's fair enough. Except for colored text, the rest could be handled by markdown, but then I'm just assuming things. I was using phixiv for some discord bot, and having markdown output from the API was something I wished for. If that's not something you wish for the project, I understand and thank you for your time.

**Comment by thelaao** [comment]
I don't think it's ideal to implement markdown conversion here as other projects might need the description in a different format. It is better to let api users convert the html to whatever format they need.
