### ISSUE TITLE
phixiv urls with :index do not appear to be working

### ISSUE THREAD

**Issue by nicoya** [thelaao/phixiv#5]
Steps:

1.  Paste a link in the format of /:language/artworks/:id in Discord
2.  Paste a link in the format of /:language/artworks/:id/:index with a valid index in a multi-image post

Expected:

Both links preview

Actual:

Link in step 1 shows a preview, link in step 2 shows nothing at all.

**Comment by thelaao** [comment]
The errors I found in the logs for the :index path were either dead pixiv ids or urls with extra stuff at the end such as https://www.phixiv.net/en/artworks/124041962/2|| (same problem as #2).
I have deployed a fix to the latter, feel free to reopen the issue if the issue stills persists.

**Comment by nicoya** [comment]
Seems to be working now, thanks!
