### ISSUE TITLE
How to get multiple image embed working

### ISSUE THREAD

**Issue by TynotWolfDragon** [thelaao/phixiv#6]
I have tried using the /<index> the link with the phixiv style link, but it's not working. Is there supposed to be a space somewhere?

`https://www.phixiv.net/en/artworks/#######/<index>`

Is basically what I posted, but it doesn't embed the extra images.

**Comment by TynotWolfDragon** [comment]
Multiple edits to get the markdown working

**Comment by thelaao** [comment]
You are using the correct link, it shouldn't have any spaces on it, example: https://www.phixiv.net/en/artworks/124748386/2 (note that this will embed only the second image, if you want every image you need to send one link for each).
Do you have any examples of links that aren't working? I don't see any errors in the logs.

**Comment by TynotWolfDragon** [comment]
Wait, am I supposed to change the <index> into a number? Cause that's not clear in the instructions.

**Comment by thelaao** [comment]
Yes, you are supposed to replace the values of the fields that start with a colon (:id, :index and :language).
I added some examples to the README to make the instructions clearer.

**Comment by TynotWolfDragon** [comment]
Thank you. I'll close this now.
